name: Build and Deploy
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate hashes and update files
        run: |
          # Generate hashes
          RECIPES_HASH=$(sha256sum recipes.js | cut -c1-8)
          COMPONENTS_HASH=$(sha256sum components.js | cut -c1-8)
          STYLES_HASH=$(sha256sum styles.css | cut -c1-8)
          
          # Print hashes for debugging
          echo "Generated hashes:"
          echo "recipes.js: $RECIPES_HASH"
          echo "components.js: $COMPONENTS_HASH"
          echo "styles.css: $STYLES_HASH"
          
          # Show an example file before changes
          echo "Before changes:"
          cat index.html
          
          # Update files with more specific patterns
          find . -name "*.html" -type f -exec sed -i 's/href="styles.css"/href="styles.css?h='$STYLES_HASH'"/' {} +
          find . -name "*.html" -type f -exec sed -i 's/src="recipes.js"/src="recipes.js?h='$RECIPES_HASH'"/' {} +
          find . -name "*.html" -type f -exec sed -i 's/src="components.js"/src="components.js?h='$COMPONENTS_HASH'"/' {} +
          
          # Show an example file after changes
          echo "After changes:"
          cat index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
